### ISSUE TITLE
Sometimes doesn't program correctly on power on. 

### ISSUE THREAD

**Issue by ON1AVO** [g4eml/RP2040_Synth#1]
MAX2780 6GHz synth., it works fine, only the settings aren't saved.
After powering up the synth, it generates the highest possible freq. 6029MHz and not the saved settings.
Verifying the settings with Putty all seems OK, attached a screenshot.

![RP2040-Synth](https://github.com/user-attachments/assets/5e921672-0008-43ad-af49-f26d0bd99c90)

**Comment by g4eml** [comment]
It looks like it is saving the settings but for some reason the chip is not programming correctly on power up. This may be a problem with the power on reset.Please try the following .. Power on. Enter C to calculate and display the current settings. Make sure they look OK. That proves they are being saved OK. Then try setting the frequency again using the F command.Does it output OK at that point? The only time I have seen similar things before is when the connecting leads to the synthesiser were too long. If you are using leads longer than about 50mm it might be worth shortening them. Colin G4EMLOn 23 Jul 2024 14:17, ON1AVO ***@***.***> wrote:
MAX2780 6GHz synth., it works fine, only the settings aren't saved.
After powering up the synth, it generates the highest possible freq. 6029MHz and not the saved settings.
Verifying the settings with Putty all seems OK, attached a screenshot.
RP2040-Synth.jpg (view on web)

**Comment by ON1AVO** [comment]
Colin,

Tnx for the quick reply.
Same result. Attached a photo of my quick PCB setup and Putty with the
suggested commands.
The SPI leads are shorter than 20mm, just the powerleads are a bit longer.

[image: image.png]

73 Freddy

Op di 23 jul 2024 om 16:17 schreef g4eml ***@***.***>:

> It looks like it is saving the settings but for some reason the chip is
> not programming correctly on power up. This may be a problem with the power
> on reset.Please try the following .. Power on. Enter C to calculate and
> display the current settings. Make sure they look OK. That proves they are
> being saved OK. Then try setting the frequency again using the F
> command.Does it output OK at that point? The only time I have seen similar
> things before is when the connecting leads to the synthesiser were too
> long. If you are using leads longer than about 50mm it might be worth

**Comment by g4eml** [comment]
It is not clear from your message.Has it ever produced the correct output frequency? Does it only go wrong when you power cycle it?I have one here that has been working for a long time. I will test it with the same settings as you are using. Colin. On 23 Jul 2024 15:54, ON1AVO ***@***.***> wrote:
Colin,



Tnx for the quick reply.

Same result. Attached a photo of my quick PCB setup and Putty with the

suggested commands.

The SPI leads are shorter than 20mm, just the powerleads are a bit longer.



[image: image.png]



73 Freddy



Op di 23 jul 2024 om 16:17 schreef g4eml ***@***.***>:



> It looks like it is saving the settings but for some reason the chip is

> not programming correctly on power up. This may be a problem with the power

> on reset.Please try the following .. Power on. Enter C to calculate and

> display the current settings. Make sure they look OK. That proves they are

> being saved OK. Then try setting the frequency again using the F

> command.Does it output OK at that point? The only time I have seen similar

> things before is when the connecting leads to the synthesiser were too

> long. If you are using leads longer than about 50mm it might be worth

**Comment by ON1AVO** [comment]
Colin,

Yes it produces the right output frequency as shown in the Putty screenshot.
After disconnecting the USB lead, powering down, and powering up with the 5V PCB power connector, the output is 6GHz instead of the programmed frequency. The same when powering up with the USB lead.

**Comment by ON1AVO** [comment]
Just a comparision between EML and JNT

![G4EML vs G4JNT](https://github.com/user-attachments/assets/e941c6d2-34f8-4592-b915-6473bb638a2f)

**Comment by g4eml** [comment]
Those differences in register values are insignificant. Both will work. 

There are so many different settings available that there is no single 'correct' set of values. Fine tuning of all the register values may sometimes improve the output quality. This is best done using the chip data sheet and the V command to change individual parameters. 

I have tried your settings on my device and it works Ok on power up. So it looks like your chip for some reason is not recognising the first register download. 

Please try the attached firmware. This has been modified to program the chip twice on power up. 

[RP2040SynthTest.zip](https://github.com/user-attachments/files/16354112/RP2040SynthTest.zip)

Colin.

**Comment by ON1AVO** [comment]
Colin,

Your modification did the trick, spot on frequency after powering up.
Tnx for the quick fix.

Freddy

Op di 23 jul 2024 om 22:45 schreef g4eml ***@***.***>:

**Comment by g4eml** [comment]
OK, thanks for the feedback. I will include the fix in the next release. Colin. On 24 Jul 2024 07:52, ON1AVO ***@***.***> wrote:
Colin,



Your modification did the trick, spot on frequency after powering up.

Tnx for the quick fix.



Freddy



Op di 23 jul 2024 om 22:45 schreef g4eml ***@***.***>:

**Comment by g4eml** [comment]
Now fixed with release V0.2
